# Generated by Django 2.1.5 on 2019-05-08 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.IntegerField(verbose_name='Идентификатор в erp')),
                ('title', models.CharField(max_length=100, verbose_name='Название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, verbose_name='Жанр/Категория')),
                ('word', models.CharField(help_text='Максимальное кол-во символов: 150', max_length=100, verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Ключевые слова',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='ProcessQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Максимальное кол-во символов: 300', max_length=300, verbose_name='Описание события')),
                ('start_of_work', models.DateTimeField(verbose_name='Начало работ')),
                ('end_of_work', models.DateTimeField(verbose_name='Завершение работ')),
                ('send', models.BooleanField(default=False, verbose_name='Отправить?')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processqueue', to='process.Event')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_queue', to='process.Filial')),
            ],
            options={
                'verbose_name': 'Очередь процессов',
                'verbose_name_plural': 'Очередь процессов',
            },
        ),
    ]
