# Generated by Django 2.1.5 on 2019-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_channel', models.PositiveIntegerField(verbose_name='ID канала')),
                ('name', models.CharField(max_length=250, verbose_name='Название канала')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='DvbGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Dvb код')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Dvb жанр',
                'verbose_name_plural': 'Dvb жанры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_name', models.CharField(max_length=250, verbose_name='Название передачи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('broadcast_start', models.DateTimeField(verbose_name='Начало передачи')),
                ('broadcast_end', models.DateTimeField(verbose_name='Конец передачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('category', models.ForeignKey(on_delete='Категория', related_name='program', to='core.Category')),
                ('channel', models.ForeignKey(on_delete='Канал', related_name='program', to='core.Channel')),
                ('dvb_name', models.ForeignKey(on_delete='Название dvb жанра', related_name='program', to='core.DvbGenre')),
                ('genre', models.ForeignKey(on_delete='Жанры', related_name='program', to='core.Genre')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поставщик')),
                ('main', models.BooleanField(default=False, unique=True, verbose_name='Главный?')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='provider',
            field=models.ForeignKey(on_delete='Поставщик', related_name='program', to='core.Provider'),
        ),
    ]
