# Generated by Django 2.1.5 on 2019-02-19 10:48

from django.db import migrations, models
import modules.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=modules.core.models.Channel.get_image_path, verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='dvbgenre',
            name='code',
            field=models.CharField(help_text='Максимальное кол-во символов: 4', max_length=5, verbose_name='Dvb код'),
        ),
        migrations.AlterField(
            model_name='dvbgenre',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='program',
            name='broadcast_name',
            field=models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, verbose_name='Название передачи'),
        ),
        migrations.AlterField(
            model_name='program',
            name='country',
            field=models.CharField(help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='link',
            field=models.CharField(help_text='Максимальное кол-во символов: 150', max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='login',
            field=models.CharField(blank=True, help_text='Максимальное кол-во символов: 100', max_length=100, null=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 100', max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='password',
            field=models.CharField(blank=True, help_text='Максимальное кол-во символов: 100', max_length=100, null=True, verbose_name='Пароль'),
        ),
    ]
