# Generated by Django 2.1.5 on 2019-03-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190225_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id_channel',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID канала'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete='Категория', related_name='program', to='core.Category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete='Канал', related_name='program', to='core.Channel'),
        ),
        migrations.AlterField(
            model_name='program',
            name='dvb_name',
            field=models.ForeignKey(blank=True, null=True, on_delete='Название dvb жанра', related_name='program', to='core.DvbGenre'),
        ),
        migrations.AlterField(
            model_name='program',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete='Жанры', related_name='program', to='core.Genre'),
        ),
    ]
