# Generated by Django 2.1.5 on 2019-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190305_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='provader',
            field=models.ForeignKey(blank=True, null=True, on_delete='Поставщик', related_name='channel', to='core.Provider'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id_channel',
            field=models.PositiveIntegerField(verbose_name='ID канала'),
        ),
    ]
