# Generated by Django 2.1.5 on 2019-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190305_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ssl_logo',
            field=models.BooleanField(default=False),
        ),
    ]
