# Generated by Django 2.1.5 on 2019-03-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_provider_ssl_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='ssl_logo',
            new_name='full_url_logo',
        ),
    ]
