# Generated by Django 2.1.5 on 2019-03-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190322_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Максимальное кол-во символов: 250', max_length=250, null=True, verbose_name='Название категории'),
        ),
    ]
