# Generated by Django 2.1.5 on 2019-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190325_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главный?'),
        ),
    ]
