# Generated by Django 2.1.5 on 2019-04-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190325_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='provader',
            new_name='provider',
        ),
    ]
