# Generated by Django 2.1.5 on 2019-04-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190422_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to='core.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='core.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='program',
            name='dvb_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='core.DvbGenre', verbose_name='dvb жанр'),
        ),
        migrations.AlterField(
            model_name='program',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program', to='core.Genre', verbose_name='Жанр'),
        ),
    ]
