# Generated by Django 2.1.5 on 2019-04-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190422_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='country',
        ),
    ]
