# Generated by Django 2.1.5 on 2019-04-23 08:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_program_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='broadcast_end',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 23, 8, 17, 38, 156656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='program',
            name='broadcast_start',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 23, 8, 17, 38, 156635, tzinfo=utc)),
        ),
    ]
