# Generated by Django 2.1.5 on 2019-04-23 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190423_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='broadcast_end',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='program',
            name='broadcast_start',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
