# Generated by Django 2.1.5 on 2019-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190423_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='broadcast_end',
            field=models.DateTimeField(verbose_name='Конец передачи'),
        ),
        migrations.AlterField(
            model_name='program',
            name='broadcast_start',
            field=models.DateTimeField(verbose_name='Начало передачи'),
        ),
    ]
