# Generated by Django 2.1.5 on 2019-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190423_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Отображать?'),
        ),
        migrations.AddField(
            model_name='channel',
            name='main_channel',
            field=models.BooleanField(default=False, verbose_name='Главный?'),
        ),
    ]
