# Generated by Django 2.1.5 on 2019-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190425_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='link',
            field=models.CharField(blank=True, help_text='Максимальное кол-во символов: 150', max_length=150, null=True, verbose_name='Ссылка'),
        ),
    ]
